<?php
// Id$
/**
*
* @file
*
*
* A module that provides Content type and Wrapper for creating interactive maps
* for the Lambeth.coop website
*/



/*Define a block container*/

/**
* Implements hook_block_info().
*/
function lambeth_interactive_map_block_info()
{
  /* Create multiple blocks for nodes of type interactive_map */
  $nodes = node_load_multiple(array(), array('type'=> 'interactive_map'));

  if (is_array($nodes)) {
    if (empty($nodes) != 1) {
      foreach ($nodes as $maps) {
        $blocks[$maps->nid] = array(
          // The name that will appear in the block list.
          'info'=> t('Interactive Map'. ' - ' . $maps->title),
          // Default setting.
          'cache'=> DRUPAL_CACHE_PER_ROLE,
        );
      }
      return $blocks;
    }
  }
}
function lambeth_interactive_map_block_view($delta = '')
{
  /* TODO: we should add this back in when leaflet JS releases 0.7 or greated */
  //drupal_add_js('http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js', 'external');
     
  // Load the node according to the ID from the delta
  $delta = str_replace('interactive_map_','',$delta);
  $block['subject'] = t('Interactive Map');
  // load the node containing settings for this map
  $node     = node_load($delta);
  // Set the variable names

  $feed_url = isset($node->field_feed_url['und'][0]['value']) ? $node->field_feed_url['und'][0]['value'] : '' ;
  $polygon_url = isset($node->field_polygon_url['und'][0]['value']) ? $node->field_polygon_url['und'][0]['value'] : '';
  $fixed_layer_url = isset($node->field_fixed_layer_url['und'][0]['value']) ? $node->field_fixed_layer_url['und'][0]['value'] : '';
  $map_zoom = isset($node->field_map_zoom['und'][0]['value']) ? $node->field_map_zoom['und'][0]['value'] : '';
  $map_height = isset($node->field_map_height['und'][0]['value']) ? $node->field_map_height['und'][0]['value'] : '';
  $map_width = isset($node->field_map_width['und'][0]['value']) ? $node->field_map_width['und'][0]['value'] : '';
  $map_search_type = isset($node->field_location_search_type['und'][0]['value']) ? $node->field_location_search_type['und'][0]['value'] : '';
  $map_display_filter_on = isset($node->field_places_filter_on['und'][0]['value']) ? $node->field_places_filter_on['und'][0]['value'] : '';
  $map_centre = isset($node->field_centre_co_ord_x['und'][0]['value']) ? $node->field_centre_co_ord_x['und'][0]['value'] . ' , ' . $node->field_centre_co_ord_y['und'][0]['value'] : '';

  // Retrieve and process data here.
  $block['content'] = t('<div class="lambeth_map" data-map-url="'. $feed_url . '" ' .
    ' data-map-zoom="' . $map_zoom . '" data-map-centre="' . $map_centre . '" data-map-width="'. $map_width . '" data-map-outline-url="' . $polygon_url . '"  data-map-height="' . $map_height . '" data-map-search-type="' . $map_search_type . '" data-map-postcode-search="true" data-map-filter-on="' . $map_display_filter_on .  '" data-map-fixed-layer-url="' . $fixed_layer_url . '"></div>');


  $block['title'] = $node->title;
  return $block;
}

/**
*
* Implements hook_permission()
*
* Enables a permission tab in the Drupal permissions administration
*
*/
function lambeth_interactive_map_permission()
{
  return array(
    'Administer Lambeth Council Interactive Map module' => array(
      'title'      => t('Administer Lambeth Council Interactive Map module'),
      'description'=> t('Users with this permission are able to administer Lambeth Interactive Maps module'),
    ),

  );
}

/**
* Implements hook_help
*
* Provides help for the Interactive Map Module
*
*/

function lambeth_interactive_map_help($path, $arg)
{
  if ($path == 'admin/help#lambeth_interactive_map') {
    $helpText = '<h2>Lambeth.coop Interactive Maps</h2>';
    $helpText .= 'Current functions of the Interactive Maps module. ';

    return t($helpText);
  }
}

/**
*  implements hook_menu()
*
*  Adds menu item for Lambeth Interactive Map to Config menu
*/

function lambeth_interactive_map_menu()
{
  $items['admin/config/maps'] = array(
    'title'           => 'Lambeth Interactive Maps Settings',
    'access arguments' => array('Administer Lambeth Council Interactive Map module'),
    'page arguments'                       => array('lambeth_interactive_map_arguments_settings'),
    'page callback'   => 'drupal_get_form',
  );

  return $items;
}



function lambeth_interactive_map_arguments_settings($form, & $form_state)
{
  $form['lambeth_interactive_map_geojson_url'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Default Feed URL'),
    '#description'  => t('Set the default base URL for the GeoJSon feed that maps will be using'),
    '#max_length'   => 120,
    '#size'         => 80,
    '#required'     => TRUE,
    '#default_value'=> variable_get('lambeth_interactive_map_geojson_url'),
  );



  return system_settings_form($form);
}









